---
# `env TMPDIR=/tmp` is needed to set TMPDIR with cleanenv
singularity-args: "\
  -B $PWD,/tmp \
  -H $(mktemp -d) \
  --pwd $PWD \
  --env TMPDIR=/tmp \
  --env LC_ALL=C \
  --containall --cleanenv --writable-tmpfs"
use-singularity: true
use-conda: False
